// 日本語の国名・地域名を英語に変換するマッピング

const countryNameMap: Record<string, string> = {
  'イギリス': 'United Kingdom',
  'アメリカ': 'United States',
  'オーストラリア': 'Australia',
  'カナダ': 'Canada',
  'ニュージーランド': 'New Zealand',
  'アイルランド': 'Ireland',
  'シンガポール': 'Singapore',
  '南アフリカ': 'South Africa',
  'インド': 'India',
  '中国': 'China',
  '日本': 'Japan',
  '韓国': 'South Korea',
  'フランス': 'France',
  'ドイツ': 'Germany',
  'イタリア': 'Italy',
  'スペイン': 'Spain',
  'ポルトガル': 'Portugal',
  'ロシア': 'Russia',
  'ブラジル': 'Brazil',
  'メキシコ': 'Mexico',
  'アルゼンチン': 'Argentina',
  'チリ': 'Chile',
  'ペルー': 'Peru',
  'コロンビア': 'Colombia',
  'ベネズエラ': 'Venezuela',
  'エクアドル': 'Ecuador',
  'ボリビア': 'Bolivia',
  'パラグアイ': 'Paraguay',
  'ウルグアイ': 'Uruguay',
  'フィリピン': 'Philippines',
  'インドネシア': 'Indonesia',
  'マレーシア': 'Malaysia',
  'タイ': 'Thailand',
  'ベトナム': 'Vietnam',
  'カンボジア': 'Cambodia',
  'ラオス': 'Laos',
  'ミャンマー': 'Myanmar',
  'バングラデシュ': 'Bangladesh',
  'パキスタン': 'Pakistan',
  'スリランカ': 'Sri Lanka',
  'ネパール': 'Nepal',
  'ブータン': 'Bhutan',
  'モンゴル': 'Mongolia',
  'カザフスタン': 'Kazakhstan',
  'ウズベキスタン': 'Uzbekistan',
  'トルクメニスタン': 'Turkmenistan',
  'キルギス': 'Kyrgyzstan',
  'タジキスタン': 'Tajikistan',
  'アフガニスタン': 'Afghanistan',
  'イラン': 'Iran',
  'イラク': 'Iraq',
  'サウジアラビア': 'Saudi Arabia',
  'アラブ首長国連邦': 'United Arab Emirates',
  'エジプト': 'Egypt',
  'モロッコ': 'Morocco',
  'アルジェリア': 'Algeria',
  'チュニジア': 'Tunisia',
  'リビア': 'Libya',
  'スーダン': 'Sudan',
  'エチオピア': 'Ethiopia',
  'ケニア': 'Kenya',
  'タンザニア': 'Tanzania',
  'ウガンダ': 'Uganda',
  'ルワンダ': 'Rwanda',
  'ガーナ': 'Ghana',
  'ナイジェリア': 'Nigeria',
  'セネガル': 'Senegal',
  'マリ': 'Mali',
  'ブルキナファソ': 'Burkina Faso',
  'ニジェール': 'Niger',
  'チャド': 'Chad',
  'カメルーン': 'Cameroon',
  'ガボン': 'Gabon',
  'コンゴ': 'Congo',
  'アンゴラ': 'Angola',
  'モザンビーク': 'Mozambique',
  'マダガスカル': 'Madagascar',
  'モーリシャス': 'Mauritius',
  'セーシェル': 'Seychelles',
  'ジンバブエ': 'Zimbabwe',
  'ザンビア': 'Zambia',
  'マラウィ': 'Malawi',
  'ボツワナ': 'Botswana',
  'ナミビア': 'Namibia',
  'レソト': 'Lesotho',
  'スワジランド': 'Eswatini',
  'ギリシャ': 'Greece',
  'トルコ': 'Turkey',
  'イスラエル': 'Israel',
  'ヨルダン': 'Jordan',
  'レバノン': 'Lebanon',
  'シリア': 'Syria',
  'イエメン': 'Yemen',
  'オマーン': 'Oman',
  'クウェート': 'Kuwait',
  'バーレーン': 'Bahrain',
  'カタール': 'Qatar',
  'ポーランド': 'Poland',
  'チェコ': 'Czech Republic',
  'スロバキア': 'Slovakia',
  'ハンガリー': 'Hungary',
  'ルーマニア': 'Romania',
  'ブルガリア': 'Bulgaria',
  'セルビア': 'Serbia',
  'クロアチア': 'Croatia',
  'ボスニア・ヘルツェゴビナ': 'Bosnia and Herzegovina',
  'スロベニア': 'Slovenia',
  'マケドニア': 'North Macedonia',
  'アルバニア': 'Albania',
  'モンテネグロ': 'Montenegro',
  'コソボ': 'Kosovo',
  'モルドバ': 'Moldova',
  'ウクライナ': 'Ukraine',
  'ベラルーシ': 'Belarus',
  'リトアニア': 'Lithuania',
  'ラトビア': 'Latvia',
  'エストニア': 'Estonia',
  'フィンランド': 'Finland',
  'スウェーデン': 'Sweden',
  'ノルウェー': 'Norway',
  'デンマーク': 'Denmark',
  'アイスランド': 'Iceland',
  'オランダ': 'Netherlands',
  'ベルギー': 'Belgium',
  'ルクセンブルク': 'Luxembourg',
  'スイス': 'Switzerland',
  'オーストリア': 'Austria',
  '台湾': 'Taiwan',
  '香港': 'Hong Kong',
  'マカオ': 'Macau',
  '北朝鮮': 'North Korea',
  'パレスチナ': 'Palestine',
  '西サハラ': 'Western Sahara',
  'エリトリア': 'Eritrea',
  'ジブチ': 'Djibouti',
  'ソマリア': 'Somalia',
  'ブルンジ': 'Burundi',
  'ギニアビサウ': 'Guinea-Bissau',
  'ギニア': 'Guinea',
  'シエラレオネ': 'Sierra Leone',
  'リベリア': 'Liberia',
  'コートジボワール': 'Ivory Coast',
  'トーゴ': 'Togo',
  'ベナン': 'Benin',
  '赤道ギニア': 'Equatorial Guinea',
  'コンゴ共和国': 'Republic of the Congo',
  'コンゴ民主共和国': 'Democratic Republic of the Congo',
  '中央アフリカ': 'Central African Republic',
  'グアテマラ': 'Guatemala',
  'ベリーズ': 'Belize',
  'エルサルバドル': 'El Salvador',
  'ホンジュラス': 'Honduras',
  'ニカラグア': 'Nicaragua',
  'コスタリカ': 'Costa Rica',
  'パナマ': 'Panama',
  'キューバ': 'Cuba',
  'ジャマイカ': 'Jamaica',
  'ハイチ': 'Haiti',
  'ドミニカ共和国': 'Dominican Republic',
  'プエルトリコ': 'Puerto Rico',
  'トリニダード・トバゴ': 'Trinidad and Tobago',
  'バルバドス': 'Barbados',
  'バハマ': 'Bahamas',
  'ガイアナ': 'Guyana',
  'スリナム': 'Suriname',
  'フランス領ギアナ': 'French Guiana',
  'フォークランド諸島': 'Falkland Islands',
  'パプアニューギニア': 'Papua New Guinea',
  'フィジー': 'Fiji',
  'ソロモン諸島': 'Solomon Islands',
  'バヌアツ': 'Vanuatu',
  'ニューカレドニア': 'New Caledonia',
  'フランス領ポリネシア': 'French Polynesia',
  'サモア': 'Samoa',
  'トンガ': 'Tonga',
  'キリバス': 'Kiribati',
  'ミクロネシア': 'Micronesia',
  'マーシャル諸島': 'Marshall Islands',
  'パラオ': 'Palau',
  'ナウル': 'Nauru',
  'ツバル': 'Tuvalu',
  'ブルネイ': 'Brunei',
  '東ティモール': 'East Timor',
  'ソウル': 'Seoul',
  '釜山': 'Busan',
  '済州島': 'Jeju Island',
  'アゼルバイジャン': 'Azerbaijan',
  'タシュケント': 'Tashkent',
  'コモロ': 'Comoros',
  // 日本の地域名
  '関東地方': 'Kanto Region',
  '関西地方': 'Kansai Region',
  '福岡県': 'Fukuoka Prefecture',
  '青森県': 'Aomori Prefecture',
  '愛知県': 'Aichi Prefecture',
  '広島県': 'Hiroshima Prefecture',
  '鹿児島県': 'Kagoshima Prefecture',
  '沖縄県': 'Okinawa Prefecture',
  '宮城県': 'Miyagi Prefecture',
  '北海道': 'Hokkaido',
  '北京': 'Beijing',
  '上海': 'Shanghai',
  '台湾': 'Taiwan',
  '北中部': 'North Central',
  'ウッタル・プラデーシュ': 'Uttar Pradesh',
  'デリー': 'Delhi',
  'タミル・ナードゥ': 'Tamil Nadu',
  'アーンドラ・プラデーシュ': 'Andhra Pradesh',
  'テランガーナ': 'Telangana',
  'カルナータカ': 'Karnataka',
  'マイソール': 'Mysore',
  'ケーララ': 'Kerala',
  '北部': 'North',
  'オディシャ': 'Odisha',
  'グワーハーティー': 'Guwahati',
  'バンコク': 'Bangkok',
  'チェンマイ': 'Chiang Mai',
  '南部': 'South',
  'ハノイ': 'Hanoi',
  'ホーチミン': 'Ho Chi Minh City',
  'フエ': 'Hue',
  'ヤンゴン': 'Yangon',
  'マンダレー': 'Mandalay',
  'ラサ': 'Lhasa',
  '西部': 'West',
  'ポートモレスビー': 'Port Moresby',
  'アディスアベバ': 'Addis Ababa',
  '南西部（オヨ系）': 'Southwest (Oyo)',
  'オグン州エグバ': 'Ogun State (Egba)',
  'エキティ州': 'Ekiti State',
  'オンド州': 'Ondo State',
  'オグン州イジェブ': 'Ogun State (Ijebu)',
  '南東部': 'Southeast',
  'クワズール・ナタール': 'KwaZulu-Natal',
  'ハウテン/クワズール・ナタール都市部': 'Gauteng/KwaZulu-Natal Urban',
  'クワズール・ナタール北部': 'Northern KwaZulu-Natal',
  '東ケープ': 'Eastern Cape',
  '西ケープ': 'Western Cape',
  '東部/国境地帯': 'Eastern/Border Region',
  '中央高地': 'Central Highlands',
  '全国': 'Nationwide',
  '東ジャワ（スラバヤ）': 'East Java (Surabaya)',
  'イスタンブール': 'Istanbul',
  'イズミル': 'Izmir',
  'エルズルム/ヴァン': 'Erzurum/Van',
  '広東省・香港': 'Guangdong/Hong Kong',
  '客家地区': 'Hakka Regions',
  '福建省': 'Fujian',
  '潮州': 'Chaozhou',
  '海南省': 'Hainan',
  '温州': 'Wenzhou',
  '蘇州': 'Suzhou',
  '杭州': 'Hangzhou',
  '寧波': 'Ningbo',
  '福州': 'Fuzhou',
  '厦門': 'Xiamen',
  '南昌': 'Nanchang',
  '長沙': 'Changsha',
  '武漢': 'Wuhan',
  '成都': 'Chengdu',
  '昆明': 'Kunming',
  '貴陽': 'Guiyang',
  '南寧': 'Nanning',
  '海口': 'Haikou',
  '台北': 'Taipei',
  '香港': 'Hong Kong',
  'トスカーナ': 'Tuscany',
  'カンパニア': 'Campania',
  'ラツィオ': 'Lazio',
  'シチリア': 'Sicily',
  'ヴェネト': 'Veneto',
  'ロンバルディア': 'Lombardy',
  'サルデーニャ': 'Sardinia',
  'ストックホルム': 'Stockholm',
  'コペンハーゲン': 'Copenhagen',
  'ユトランド半島': 'Jutland',
  'ヘルシンキ': 'Helsinki',
  'トゥルク': 'Turku',
  'ワルシャワ': 'Warsaw',
  'クラクフ': 'Krakow',
  'キーウ': 'Kyiv',
  'リヴィウ': 'Lviv',
  'ソフィア': 'Sofia',
  'ザグレブ': 'Zagreb',
  'ベオグラード': 'Belgrade',
  'リュブリャナ': 'Ljubljana',
  'スコピエ': 'Skopje',
  'ビリニュス': 'Vilnius',
  'リガ': 'Riga',
  'タリン': 'Tallinn',
  'アテネ': 'Athens',
  'キプロス': 'Cyprus',
  '湾岸諸国': 'Gulf States',
  'レバント': 'Levant',
  'モロッコ/アルジェリア/チュニジア': 'Morocco/Algeria/Tunisia',
  'モスクワ': 'Moscow',
  'サンクトペテルブルク': 'Saint Petersburg',
  'ロストフ/クバーニ': 'Rostov/Kuban',
  'モンゴル国': 'Mongolia',
  'レイキャヴィーク': 'Reykjavik',
  'ペシャーワル': 'Peshawar',
  'カンダハール': 'Kandahar',
  'トルコ・シリア・イラク北部': 'Turkey/Syria/Northern Iraq',
  'イラク・イラン西部': 'Western Iraq/Iran',
  'グジャラート': 'Gujarat',
  'スーラト': 'Surat',
  'マハーラーシュトラ': 'Maharashtra',
  '北東部': 'Northeast'
};

/**
 * 地域名（国名または地域名）を現在の言語に応じて返す
 */
export function getRegionName(regionJa: string, currentLang: string = 'ja'): string {
  if (currentLang === 'en') {
    // まず2文字の国コードとして解釈を試みる
    if (regionJa && regionJa.length === 2) {
      try {
        const countryName = new Intl.DisplayNames(['en'], { type: 'region' }).of(regionJa);
        if (countryName && countryName !== regionJa) {
          return countryName;
        }
      } catch {}
    }
    // マッピングから検索
    return countryNameMap[regionJa] || regionJa;
  }
  return regionJa;
}

